### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by verygladen** [ChaoticPumpkin/YW-Research#1]
I found this today and it has some very great tools and resources! Something I wanted to ask is if we've found out the workings of the RES.bin's. I'm asking this because there's a tool called Metanoia which can rip Level-5 models, but it always complains the RES.bin is corrupt, while other Level-5 games are fine.

**Comment by ChaoticPumpkin** [comment]
Hmm, I haven't done much with the 3d models in the game so I'm probably not the best person to ask, but if I find anything useful I'll let you know.

**Comment by verygladen** [comment]
Got it!
